### ISSUE TITLE
App doesn't start

### ISSUE THREAD

**Issue by jayeshcp** [Mpmart08/MusicPlayer#20] opened 2016-06-17 12:52 UTC
**Jar File:**  `releases/MusicPlayer_v1.1.jar`
**OS:** Mac (OS X El Capitan, Version 10.11.5)
**Java:** Java 1.8.0 (Build 1.8.0-b132). 

App doesn't load and only splash screen stays.

Warning message shown in terminal:

```
2016-06-17 08:43:45.747 java[17421:403574] 08:43:45.747 WARNING:  140: 
This application, or a library it uses, is using the deprecated Carbon Component 
Manager for hosting Audio Units. Support for this will be removed in a future release. 
Also, this makes the host incompatible with version 3 audio units. Please transition 
to the API's in AudioComponent.h
```

**Note:** Previous version `MusicPlayer_v1.0.2.jar` works fine without any issues.

**Screenshot:**

![screen shot 2016-06-17 at 8 45 09 am](https://cloud.githubusercontent.com/assets/4054338/16151042/bc6ac494-3468-11e6-888b-7f9bd73897fa.png)

**Comment by GerardoPrada** [comment] 2016-06-17 16:35
It seems like this issue is being caused by the external library used to enable media key functionality on keyboards. We're looking into possible solutions. Thanks for letting us know!

**Comment by GerardoPrada** [comment] 2016-06-18 04:30
Should be fixed with latest commit.

**Closed by GerardoPrada** 2016-06-18 04:30 UTC
